import { MainService } from './../../services/main.service';
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import * as XLSX from 'xlsx';

@Component({
  selector: 'app-main',
  templateUrl: './main.component.html',
  styleUrls: ['./main.component.css'],
})
export class MainComponent implements OnInit {
  constructor(private mainService: MainService) {
    this.mainService.setExporting(false);
  }

  @ViewChild('myButton')
  myButton!: ElementRef<HTMLElement>;
  @ViewChild('myCloseButton')
  myCloseButton!: ElementRef<HTMLElement>;

  modalMessage = '';

  getExporting() {
    return this.mainService.getExporting();
  }

  getDownloading() {
    return this.mainService.getDownloading();
  }

  getFinishedOperation(){
    return this.mainService.getFinishedOperation();
  }

  showModal(message: string) {
    this.modalMessage = message;
    let el: HTMLElement = this.myButton?.nativeElement;
    el.click();
  }

  closeModal() {
    let el: HTMLElement = this.myCloseButton?.nativeElement;
    el.click();
  }

  original_urls_list = this.mainService.original_urls_list;

  //List of endpoints generated by API
  endpointsList = this.mainService.getEndpointList();

  //sends the url list main service function that send to the backend and generates the endpoints
  sendRequestUsingList() {
    if (this.original_urls_list.length == 1) {
      this.showModal('Faça o upload da lista de links!!');
    } else {
      this.showModal(
        'Exportando Comentários! Essa operação pode demorar vários minutos'
      );
      //this.mainService.setExporting(true);
      console.log('criando arquivos de download no servidor da api');
      this.mainService.sendRequestUsingList();
    }
  }

  //Send the requests to Endpoints List to download the files from API
  sendRequestToEndpoints() {
    console.log('Inciando downloads');
    this.mainService.sendRequestToEndpoints();
  }

  //Open and read the xlsx file to get the url list
  onFileChange(ev: any) {
    /* wire up file reader */
    const target: DataTransfer = <DataTransfer>ev.target;
    if (target.files.length !== 1) throw new Error('Cannot use multiple files');
    const reader: FileReader = new FileReader();
    reader.onload = (e: any) => {
      /* read workbook */
      const bstr: string = e.target.result;
      const wb: XLSX.WorkBook = XLSX.read(bstr, { type: 'binary' });

      /* grab first sheet */
      const wsname: string = wb.SheetNames[0];
      const ws: XLSX.WorkSheet = wb.Sheets[wsname];

      /* save data */
      let json_data = XLSX.utils.sheet_to_json(ws, { header: 1 });

      json_data.map((item) => {
        let item_str = String(item);
        if (item_str != '') this.mainService.original_urls_list.push(item_str);
      });
      this.mainService.original_urls_list =
        this.mainService.original_urls_list.slice(1);
      console.log(this.mainService.original_urls_list);
      let tam = this.original_urls_list.length;
      this.showModal('Foram carregados ' + String(tam - 1) + ' Links!');
    };
    reader.readAsBinaryString(target.files[0]);
  }

  teste() {
    //this.mainService.test()
    this.mainService.sendRequestUsingList();
  }
  ngOnInit(): void {}
}
