import { MainService } from './../../services/main.service';
import { Component, OnInit } from '@angular/core';
import * as XLSX from 'xlsx';
import { stringify } from 'querystring';

@Component({
  selector: 'app-main',
  templateUrl: './main.component.html',
  styleUrls: ['./main.component.css'],
})
export class MainComponent implements OnInit {
  constructor(private mainService: MainService) {}

  original_urls_list = this.mainService.original_urls_list;

  //List of endpoints generated by API
  endpointsList = this.mainService.getEndpointList();

  //sends the url list main service function that send to the backend and generates the endpoints
  sendRequestUsingList() {
    console.log('criando arquivos de download no servidor da api');
    this.mainService.sendRequestUsingList();
  }

  //Send the requests to Endpoints List to download the files from API
  sendRequestToEndpoints() {
    console.log('Inciando downloads');
    this.mainService.sendRequestToEndpoints();
  }

  //Open and read the xlsx file to get the url list
  onFileChange(ev: any) {
    /* wire up file reader */
    const target: DataTransfer = <DataTransfer>ev.target;
    if (target.files.length !== 1) throw new Error('Cannot use multiple files');
    const reader: FileReader = new FileReader();
    reader.onload = (e: any) => {
      /* read workbook */
      const bstr: string = e.target.result;
      const wb: XLSX.WorkBook = XLSX.read(bstr, { type: 'binary' });

      /* grab first sheet */
      const wsname: string = wb.SheetNames[0];
      const ws: XLSX.WorkSheet = wb.Sheets[wsname];

      /* save data */
      let json_data = XLSX.utils.sheet_to_json(ws, { header: 1 });

      json_data.map((item) => {
        let item_str = String(item);
        if (item_str != '') this.mainService.original_urls_list.push(item_str);
      });
      this.mainService.original_urls_list =
        this.mainService.original_urls_list.slice(1);
      console.log(this.mainService.original_urls_list);
    };
    reader.readAsBinaryString(target.files[0]);
  }

  teste() {
    //this.mainService.test()
    this.mainService.sendRequestUsingList();
  }
  ngOnInit(): void {

  }
}
